### ISSUE TITLE
Enable other common video file formats

### ISSUE THREAD

**Issue by saulalbert** [HiLabTufts/gailbot#17]
.MXF is quite an unusual video file format. There's no reason we can't use ffmpeg to convert pretty much any other common video file format using Gailbot. I'd recommend at least enabling Gailbot to use .mov, .mp4, .m4v, and .avi - I don't think this would require any additional code, since FFMPEG handles these formats without any problem using the same flags as an MXF file.

**Comment by mumair01** [comment]
For this version of Gailbot, which was operating under the assumptions that the input would be MXF or wav, this request has been implemented with the following limitations:
1. We have to convert the mp4, mov, m4v, or avi file to wav before use. Gailbot does this automatically.
2. The dialogue model for a single file can be used.
3. Two separate files can be used if they correspond to the same conversation.'

However, one of these files can not be used to extract audio from separate channels, which we can do with MXF files because they are guaranteed to have more than one audio channel.

**Comment by saulalbert** [comment]
That makes perfect sense - if Gailbot automatically processes video files to Wav then it already does this - nice one!
