### ISSUE TITLE
Word timing Issues

### ISSUE THREAD

**Issue by mumair01** [HiLabTufts/gailbot#6]
According to the initial test results, apparently word timings are significantly off. This is a major issue. There is a need to determine if this is a problem on Watson's end or is being caused by our post-processing and turn construction functions.

**Comment by saulalbert** [comment]
As far as I can tell, these are due to both - some inaccuracy in Watson, and some over-sensitivity in our post-processing thresholds. We'll have to play around with those thresholds until we minimize the errors, but I think this is dealt with by our exiting open issue to 'tune the thresholds' ... for which we probably need to look at more transcripts.
